name: Trigger Private Workflow

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Generate token
      id: generate_token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
        repositories: fenix

    - name: Trigger workflow
      run: |
        curl -X POST \
          -H "Authorization: token ${{ steps.generate_token.outputs.token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/Ensosuru/fenix/dispatches \
          -d '{
            "event_type": "trigger-workflow",
            "client_payload": {
              "source_repo": "${{ github.repository }}",
              "ref": "${{ github.ref }}",
              "sha": "${{ github.sha }}",
              "pr_number": "${{ github.event.pull_request.number }}"
            }
          }'
